services:
  server:
    image: nginx:stable-alpine3.19
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - network
    restart: always
  app:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    environment:
      - PORT=8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./data/logs:/app/data/logs
    networks:
      - network
    restart: on-failure
  db:
    image: postgres:16.1-alpine
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Asia/Jakarta
      - PORT=${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      start_interval: 5s
      interval: 15s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7.2.5-alpine
    container_name: rediscache
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test:  ["CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_interval: 5s
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  network:
    driver: bridge
