CREATE TABLE managers (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(255) DEFAULT '',
	user_image_uri VARCHAR(4096) DEFAULT '',
	company_name VARCHAR(255) DEFAULT '',
	company_image_uri VARCHAR(4096) DEFAULT '',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
