name: Unit Testing

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.4

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Testing
      uses: robherley/go-test-action@v0.1.0
      with:
        omit: 'pie'
        testArguments: ./tests/...
